#PBS -lwalltime=24:00:00
#PBS -lselect=1:ncpus=32:mem=192gb:ngpus=8:gpu_type=RTX6000

module load anaconda3/personal
module load cuda

source activate dl-fx-forecasting
conda install tensorflow-gpu
conda install -c conda-forge pyarrow

echo $PBS_O_WORKDIR

pip install -r $PBS_O_WORKDIR/requirements.txt

export ROOT_DIR=$PBS_O_WORKDIR

python $PBS_O_WORKDIR/src/models/train_model.py

mkdir $WORK/$PBS_JOBID
cp -r . $WORK/$PBS_JOBID
echo "JOB FINISHED"