
name: Project Build

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jpxkqx/dl-fx-forecasting:firsttry
